#!/bin/bash

# Load data
source ~/scripts/libUtils
for ((i=14; i < $(tput cols); i=i+2)); do dashes+='-'; done
data=$(cat notes | jq -r .data.notes[])
readarray -t devoir <<< $(echo "$data" | jq -r .devoir)
readarray -t codePeriode <<< $(echo "$data" | jq -r .codePeriode)
readarray -t libelleMatiere <<< $(echo "$data" | jq -r .libelleMatiere)
readarray -t typeDevoir <<< $(echo "$data" | jq -r .typeDevoir)
readarray -t coef <<< $(echo "$data" | jq -r .coef)
readarray -t noteSur <<< $(echo "$data" | jq -r .noteSur)
readarray -t valeur <<< $(echo "$data" | jq -r .valeur)
readarray -t moyenneClasse <<< $(echo "$data" | jq -r .moyenneClasse)
readarray -t minClasse <<< $(echo "$data" | jq -r .minClasse)
readarray -t maxClasse <<< $(echo "$data" | jq -r .maxClasse)
declare -A coefSubject=(["MATHEMATIQUES"]=16 ["PHYSIQUE-CHIMIE"]=16 ["PHILOSOPHIE"]=8 ["HISTOIRE-GEOGRAPHIE"]=6 ["ANGLAIS LV1"]=6 ["ESPAGNOL LV2"]=6 ["ED.PHYSIQUE & SPORT."]=6 ["ENSEIGN.SCIENTIFIQUE"]=6 ["ENS. MORAL & CIVIQUE"]=2 ["EURO ANGLAIS - DNL:Maths"]=2  ["MATHS EXPERTES"]=2)

# Display data
for ((i=0; i < "${#codePeriode[@]}"; i++)); do
  valeur[i]=$(echo $(egrep -o '[0-9]+.?[0-9]+?' <<< "${valeur[i]}") | sed 's:,:\.:')
  noteSur[i]=$(echo $(egrep -o '[0-9]+.?[0-9]+?' <<< "${noteSur[i]}") | sed 's:,:\.:')
  coef[i]=$(echo $(egrep -o '[0-9]+.?[0-9]+?' <<< "${coef[i]}") | sed 's:,:\.:')
#  currentCoefSubject="$currentCoef*${coefSubject[${libelleMatiere[i]}]}"
  if [[ "${codePeriode[i-1]}" != "${codePeriode[i]}" ]]; then
    trimester=$(egrep -o '[1-3]' <<< "${codePeriode[i]}")
    echo -e "\n$dashes TRIMESTRE $trimester $dashes\n"
  fi
  case "${typeDevoir[i]}" in
    "Interrogation écrite") typeDevoir[i]='IE  ';;
    "Devoir Surveillé") typeDevoir[i]='DS  ';;
    "Évaluation orale") typeDevoir[i]='ORAL';;
    "Devoir à la maison") typeDevoir[i]='DNS ';;
    "Travaux Pratiques") typeDevoir[i]='TP  ';;
    "Activités sportives") typeDevoir[i]='IE  ';;
  esac
  case "${libelleMatiere[i]}" in
    "ANGLAIS LV1") libelleMatiere[i]='ANG ';;
    "ED.PHYSIQUE & SPORT.") libelleMatiere[i]='EPS ';;
    "ENS. MORAL & CIVIQUE") libelleMatiere[i]='EMC ';;
    "ENSEIGN.SCIENTIFIQUE") libelleMatiere[i]='E-S ';;
    "ESPAGNOL LV2") libelleMatiere[i]='ESP ';;
    "EURO ANGLAIS - DNL:Maths") libelleMatiere[i]='EURO';;
    "HISTOIRE-GEOGRAPHIE") libelleMatiere[i]='H-G ';;
    "MATHEMATIQUES") libelleMatiere[i]='MATH';;
    "MATHS EXPERTES") libelleMatiere[i]='MEXP';;
    "PHILOSOPHIE") libelleMatiere[i]='PHI ';;
    "PHYSIQUE-CHIMIE") libelleMatiere[i]='P-C ';;
    *) echo "ERREUR : la matière ${libelleMatiere[i]} n'est pas supportée"; break;;
  esac
  if [[ -n "${valeur[i]}" && -n "${noteSur[i]}" && -n "${coef[i]}" ]]; then
    toAdd="+(${valeur[i]}/${noteSur[i]})*${coef[i]}"
    case "${libelleMatiere[i]}" in
      "ANG ") gradesANG+=("$toAdd"); coefANG+=("+${coef[i]}");;
      "EPS ") gradesEPS+=("$toAdd"); coefEPS+=("+${coef[i]}");;
      "EMC ") gradesEMC+=("$toAdd"); coefEMC+=("+${coef[i]}");;
      "E-S ") gradesES+=("$toAdd"); coefES+=("+${coef[i]}");;
      "ESP ") gradesESP+=("$toAdd"); coefESP+=("+${coef[i]}");;
      "EURO") gradesEURO+=("$toAdd"); coefEURO+=("+${coef[i]}");;
      "H-G ") gradesHG+=("$toAdd"); coefHG+=("+${coef[i]}");;
      "MATH") gradesMATHS+=("$toAdd"); coefMATHS+=("+${coef[i]}");;
      "MEXP") gradesMATHSEXP+=("$toAdd"); coefMATHSEXP+=("+${coef[i]}");;
      "PHI ") gradesPHILO+=("$toAdd"); coefPHILO+=("+${coef[i]}");;
      "P-C ") gradesPC+=("$toAdd"); coefPC+=("+${coef[i]}");;
      *) echo "ERREUR : la matière ${libelleMatiere[i]} n'est pas supportée"; break;;
    esac
  fi
  printf '%s | %s | %4.1f/%3.0f (%4.1f) | %4.1f/%4.1f/%4.1f | %s\n' "${libelleMatiere[i]}" "${typeDevoir[i]}" "${valeur[i]}" "${noteSur[i]}" "${coef[i]}" "${minClasse[i]}" "${moyenneClasse[i]}" "${maxClasse[i]}" "${devoir[i]}" | cut -c -$COLUMNS
  if [[ "${codePeriode[i]}" != "${codePeriode[i+1]}" ]]; then
    echo
    if [[ -n "$gradesANG" ]]; then printf "MOYENNE D' ANG  : %5.2f\n" $(echo "scale=3;(0${gradesANG[@]})/(0${coefANG[@]})*20" | bc); fi
    if [[ -n "$gradesEPS" ]]; then printf "MOYENNE D' EPS  : %5.2f\n" $(echo "scale=3;(0${gradesEPS[@]})/(0${coefEPS[@]})*20" | bc); fi
    if [[ -n "$gradesEMC" ]]; then printf "MOYENNE D' EMC  : %5.2f\n" $(echo "scale=3;(0${gradesEMC[@]})/(0${coefEMC[@]})*20" | bc); fi
    if [[ -n "$gradesES" ]]; then printf "MOYENNE D' E-S  : %5.2f\n" $(echo "scale=3;(0${gradesES[@]})/(0${coefES[@]})*20" | bc); fi
    if [[ -n "$gradesESP" ]]; then printf "MOYENNE D' ESP  : %5.2f\n" $(echo "scale=3;(0${gradesESP[@]})/(0${coefESP[@]})*20" | bc); fi
    if [[ -n "$gradesEURO" ]]; then printf "MOYENNE D' EURO : %5.2f\n" $(echo "scale=3;(0${gradesEURO[@]})/(0${coefEURO[@]})*20" | bc); fi
    if [[ -n "$gradesHG" ]]; then printf "MOYENNE D' H-G  : %5.2f\n" $(echo "scale=3;(0${gradesHG[@]})/(0${coefHG[@]})*20" | bc); fi
    if [[ -n "$gradesMATHS" ]]; then printf "MOYENNE DE MATH : %5.2f\n" $(echo "scale=3;(0${gradesMATHS[@]})/(0${coefMATHS[@]})*20" | bc); fi
    if [[ -n "$gradesMATHSEXP" ]]; then printf "MOYENNE DE MEXP : %5.2f\n" $(echo "scale=3;(0${gradesMATHSEXP[@]})/(0${coefMATHSEXP[@]})*20" | bc); fi
    if [[ -n "$gradesPHILO" ]]; then printf "MOYENNE DE PHI  : %5.2f\n" $(echo "scale=3;(0${gradesPHILO[@]})/(0${coefPHILO[@]})*20" | bc); fi
    if [[ -n "$gradesPC" ]]; then printf "MOYENNE DE P-C  : %5.2f\n" $(echo "scale=3;(0${gradesPC[@]})/(0${coefPC[@]})*20" | bc); fi
    unset gradesANG coefANG gradesEPS coefEPS gradesEMC coefEMC gradesES coefES gradesESP coefESP gradesEURO coefEURO gradesHG coefHG gradesMATHS coefMATHS gradesMATHSEXP coefMATHSEXP gradesPHILO coefPHILO gradesPC coefPC
  fi
done
echo
